#!/usr/bin/env bash

# "https://house.mo.gov/billtracking/bills191/jrnpdf/jrn026.pdf"

main() {
  local start="$1"; shift
  local end="$1"; shift
  for i in $(seq "${start}" "${end}"); do
    file="$(printf "jrn%03d.pdf" "${i}")"
    if [[ -f "${file}" ]]; then
      continue
    fi
    url="https://house.mo.gov/billtracking/bills191/jrnpdf/${file}"
    wget "${url}"
  done
}

main "$@"
